Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-13:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-14:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-15:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-16:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-17:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-19:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-20:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-22:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-23:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-24:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-25:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-26:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-27:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-28:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-29:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-30:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-31:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-32:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-33:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-34:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-35:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-36:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-37:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-38:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-39:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-40:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-41:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-42:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-43:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-44:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-45:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-46:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-47:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-48:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-49:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-50:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-51:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-52:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-53:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-54:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-55:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-56:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-57:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-58:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-59:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-60:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-61:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-62:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-63:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
Exception in thread Thread-64:
Traceback (most recent call last):
  File "C:\Windows\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Windows\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\btc bot\script.py", line 93, in main
    transactions = client.get_address_transactions(account_id, address_id)["data"]
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 296, in get_address_transactions
    response = self._get(
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Windows\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.NotFoundError: APIError(id=not_found): Not found
0.0028
11153.0972
0.0028
11162.9028
4
4
2
Traceback (most recent call last):
  File "C:\Windows\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Windows\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Windows\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Windows\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Windows\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Windows\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Windows\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Windows\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Windows\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Windows\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Windows\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Windows\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Windows\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Windows\lib\site-packages\urllib3\connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Windows\lib\site-packages\urllib3\connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\btc bot\main.py", line 753, in <module>
    bot.polling(none_stop=True)
  File "C:\Windows\lib\site-packages\telebot\__init__.py", line 633, in polling
    self.__threaded_polling(non_stop, interval, timeout, long_polling_timeout, allowed_updates)
  File "C:\Windows\lib\site-packages\telebot\__init__.py", line 692, in __threaded_polling
    raise e
  File "C:\Windows\lib\site-packages\telebot\__init__.py", line 654, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Windows\lib\site-packages\telebot\util.py", line 100, in raise_exceptions
    raise self.exception_info
  File "C:\Windows\lib\site-packages\telebot\util.py", line 82, in run
    task(*args, **kwargs)
  File "C:\Windows\lib\site-packages\telebot\__init__.py", line 391, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), 
  File "C:\Windows\lib\site-packages\telebot\__init__.py", line 371, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Windows\lib\site-packages\telebot\apihelper.py", line 312, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Windows\lib\site-packages\telebot\apihelper.py", line 139, in _make_request
    result = _get_req_session().request(
  File "C:\Windows\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Windows\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Windows\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
